CREATE DATABASE IF NOT EXISTS user_db;
CREATE DATABASE IF NOT EXISTS notification_db;
CREATE DATABASE IF NOT EXISTS employee_mgmt_db;
CREATE DATABASE IF NOT EXISTS leave_db;
CREATE DATABASE IF NOT EXISTS performance_db;
CREATE DATABASE IF NOT EXISTS reporting_db;
